version : '3'
services:
  app:
    build:
      dockerfile: Dockerfile_app
    ports:
      - "8080:8080"
    environment:
      DB_USER: "yildirimege" #${DB_USER}
      DB_PASSWORD: "123456" #${DB_PASSWORD}
      DB_NAME: "postgres" #${DB_NAME}
      DB_HOST: "127.0.0.1" #${DB_HOST}
      DB_PORT: "5432" #${DB_PORT}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: "yildirimege" #${POSTGRES_USER}
      POSTGRES_PASSWORD: "123456" #${POSTGRES_PASSWORD}
      POSTGRES_DB: "postgres" #${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  token_clearer:
    environment:
      - TOKEN_CLEAR_FREQUENCY=1800
    build:
      context: .
      dockerfile: Dockerfile_token_clearer
    depends_on:
      - postgres_db
    volumes:
      - ./utils:/app/utils
    command: ["python", "token_clearer.py"]  # Run the token_clearer.py script

volumes:
  db_data: