version : '3'

services:

  postgres_db:
    environment:
      POSTGRESQL_USERNAME: yildirimege
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_DB_NAME: postgres
      POSTGRESQL_HOST: postgres_db
      POSTGRESQL_DB_PORT: 5432
      TOKEN_EXPIRATION_TIME: 60
      TOKEN_CLEAR_FREQUENCY: 60
      POSTGRESQL_SSL_MODE: require

    image: postgres:13

    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRESQL_DB_PORT}:${POSTGRESQL_DB_PORT}

  app:
    environment:
      POSTGRESQL_USERNAME: yildirimege
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_DB_NAME: postgres
      POSTGRESQL_HOST: postgres_db
      POSTGRESQL_DB_PORT: 5432
      TOKEN_EXPIRATION_TIME: 60
      TOKEN_CLEAR_FREQUENCY: 60
      POSTGRESQL_SSL_MODE: require
      BACKEND_APP_PORT: 8080
    build:
      dockerfile: Dockerfile_app
      context: .


    ports:
      - 8080:8080
    depends_on:
      - postgres_db

  token_clearer:
    environment:
      POSTGRESQL_USERNAME: yildirimege
      POSTGRESQL_PASSWORD: 123456
      POSTGRESQL_DB_NAME: postgres
      POSTGRESQL_HOST: postgres_db
      POSTGRESQL_DB_PORT: 5432
      TOKEN_EXPIRATION_TIME: 60
      TOKEN_CLEAR_FREQUENCY: 60
      POSTGRESQL_SSL_MODE: require
    build:
      context: .
      dockerfile: Dockerfile_token_clearer
    depends_on:
      - postgres_db
    volumes:
      - ./utils:/app/utils
    command: ["python", "token_clearer.py"]  # Run the token_clearer.py script

volumes:
  db_data:
