name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start Docker containers and Check Their Status
      run: |
        docker-compose up --build -d
        if docker-compose ps | grep -E "flask-lightweight-token-service-app-1.*Up" && docker-compose ps | grep -E "flask-lightweight-token-service-postgres_db-1.*Up"; then
          echo "Containers are running"
        else
          echo "Containers are not running"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s unit_tests -p 'TokenAuthTests.py'
