name: Unit Tests

on: [push]

jobs:
  start_and_check_containers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Add a step to start the containers and check their status
    - name: Start Docker containers and Check Their Status
      run: |
        docker-compose up --build -d
        if docker-compose ps | grep -E "flask-lightweight-token-service_app_1.*Up" && docker-compose ps | grep -E "flask-lightweight-token-service_postgres_db_1.*Up"
        || docker-compose ps | grep -E "flask-lightweight-token-service_token_clearer-1.*Up"; then
          echo "Containers are running"
        else
          echo "Containers are not running"
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    needs: start_and_check_containers

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover -s unit_tests -p 'TokenAuthTests.py'